awards:
  storage:
    fs: {}

app:
  title: SeatGeek Backstage Plugins Demo Site
  baseUrl: http://127.0.0.1:3000

organization:
  name: SeatGeek

backend:
  baseUrl: http://127.0.0.1:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://127.0.0.1:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    guest: {}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template]
  locations:
    - type: file
      target: ../../mock-catalog/organization.yaml
    - type: file
      target: ../../mock-catalog/entities.yaml
    - type: file
      target: ../../mock-catalog/templates/create-postgres-database.yaml
    - type: file
      target: ../../mock-catalog/templates/create-python-module.yaml

slackCatalog:
  token: ${SLACK_API_TOKEN_CATALOG}

gitlabCatalog:
  host: ${GITLAB_HOST_CATALOG}
  token: ${GITLAB_TOKEN_CATALOG}
